A = float(input("Uma distancia em metros: "))
print(f"A medida de {A} corresponde a:")
print(f"{A * 0.001}Km")
print(f"{A * 0.01}Hm")
print(f"{A * 0.1:.1f}dam")
print(f"{A * 10:.0f}dm")
print(f"{A * 100:.0f}cm")
print(f"{A * 1000:.0f}mm")
