A = int(input("Digite um numero para ver sua tabuada: "))

print("-"*20)
print(f"{A} X 1 = {A * 1}")
print(f"{A} X 2 = {A * 2}")
print(f"{A} X 3 = {A * 3}")
print(f"{A} X 4 = {A * 4}")
print(f"{A} X 5 = {A * 5}")
print(f"{A} X 6 = {A * 6}")
print(f"{A} X 7 = {A * 7}")
print(f"{A} X 8 = {A * 8}")
print(f"{A} X 9 = {A * 9}")
print(f"{A} X 10 = {A * 10}")
print("-"*20)
