nome = str(input("Digite o seu nome completo: ")).strip()
print("Analisando o seu nome...")
print(f"Seu nome em MAIUSCULAS é {nome.upper()}")
print(f"Seu nome em MINUSTULAS é {nome.lower()}")
print(f"Seu nome tem ao todo {(len(nome)) - nome.count(' ')} letras")
primeiro_nome = nome.split()
print(f"Seu primeiro nome é {primeiro_nome[0]}")
